# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('opponent', models.CharField(max_length=256)),
                ('url', models.URLField(max_length=500)),
                ('home_game', models.BooleanField()),
            ],
        ),
    ]
