# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('minutes_elapsed', models.PositiveSmallIntegerField(null=True)),
                ('minutes_played', models.PositiveSmallIntegerField(null=True)),
                ('seconds_played', models.PositiveSmallIntegerField(null=True)),
                ('field_goals_made', models.PositiveSmallIntegerField(null=True)),
                ('field_goals_attempted', models.PositiveSmallIntegerField(null=True)),
                ('three_pointers_made', models.PositiveSmallIntegerField(null=True)),
                ('three_pointers_attempted', models.PositiveSmallIntegerField(null=True)),
                ('free_throws_made', models.PositiveSmallIntegerField(null=True)),
                ('free_throws_attempted', models.PositiveSmallIntegerField(null=True)),
                ('plus_minus', models.CharField(max_length=20, null=True)),
                ('offensive_rebounds', models.PositiveSmallIntegerField(null=True)),
                ('defensive_rebounds', models.PositiveSmallIntegerField(null=True)),
                ('total_rebounds', models.PositiveSmallIntegerField(null=True)),
                ('assists', models.PositiveSmallIntegerField(null=True)),
                ('turnovers', models.PositiveSmallIntegerField(null=True)),
                ('steals', models.PositiveSmallIntegerField(null=True)),
                ('blocks', models.PositiveSmallIntegerField(null=True)),
                ('blocks_against', models.PositiveSmallIntegerField(null=True)),
                ('personal_fouls', models.PositiveSmallIntegerField(null=True)),
                ('points', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='has_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='has_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='state',
            field=models.CharField(default='none', max_length=256),
        ),
    ]
