# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160331_1813'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='Game',
        ),
        migrations.AddField(
            model_name='stats',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Game'),
            preserve_default=False,
        ),
    ]
